### ISSUE TITLE
用着好好的突然报错了怎么办？

### ISSUE THREAD

**Issue by nanxun1991** [smalls0098/video-parse-tools#33]
提示Client error: `GET https://www.iesdouyin.com/web/api/v2/aweme/iteminfo?item_ids=6954125517930974500` resulted in a `444 ` response

> 58
> GuzzleHttp\Exception\ClientException 
> …/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php113
> 57
> GuzzleHttp\Exception\RequestException create
> …/vendor/guzzlehttp/guzzle/src/Middleware.php65
> 56
> GuzzleHttp\Middleware GuzzleHttp\{closure}
> …/vendor/guzzlehttp/promises/src/Promise.php203
> 55
> GuzzleHttp\Promise\Promise callHandler
> …/vendor/guzzlehttp/promises/src/Promise.php156
> 54
> GuzzleHttp\Promise\Promise GuzzleHttp\Promise\{closure}
> …/vendor/guzzlehttp/promises/src/TaskQueue.php47
> 53
> GuzzleHttp\Promise\TaskQueue run
> …/vendor/guzzlehttp/promises/src/Promise.php246
> 52
> GuzzleHttp\Promise\Promise invokeWaitFn
> …/vendor/guzzlehttp/promises/src/Promise.php223
> 51
> GuzzleHttp\Promise\Promise waitIfPending
> …/vendor/guzzlehttp/promises/src/Promise.php267
> 50
> GuzzleHttp\Promise\Promise invokeWaitList
> …/vendor/guzzlehttp/promises/src/Promise.php225

**Comment by wyq2214368** [comment]
一样，辛苦作者及时处理

**Comment by thundersword** [comment]
呼唤作者

**Comment by iseeyou** [comment]
作者已经解决了。
